# Identificación del proyecto
sonar.projectKey=shop-backend
sonar.projectName=Backend Ordenes
sonar.projectVersion=1.0

# Fuentes y pruebas
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8

# Inclusión y exclusión de archivos
sonar.java.binaries=target/classes

# Configuración de cobertura
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# URL del servidor SonarQube
sonar.host.url=http://localhost:9000

sonar.login=sqp_c7992dbf07c6c5c14f9c675c3234964830190409

